# Generated by Django 5.0.3 on 2024-03-26 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFlowItemModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cta_button_title', models.TextField(blank=True)),
                ('cta_button_url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlowModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('header_title', models.TextField(blank=True)),
                ('header_description', models.TextField(blank=True)),
                ('work_flow_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_flow.workflowitemmodel')),
            ],
        ),
    ]
