# Generated by Django 5.0.3 on 2024-03-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=255)),
                ('banner_title', models.CharField(max_length=255)),
                ('banner_description', models.TextField(max_length=255)),
                ('banner_image', models.TextField(max_length=1000)),
            ],
        ),
    ]
