# Generated by Django 5.0.3 on 2024-03-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_description', models.TextField(max_length=255)),
                ('image', models.TextField()),
                ('sub_title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
