# Generated by Django 5.0.3 on 2024-03-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurServicesModel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cta_button_title', models.CharField(max_length=255)),
                ('cta_button_url', models.CharField(max_length=255)),
            ],
        ),
    ]
