# Generated by Django 5.0.3 on 2024-03-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
        migrations.AddField(
            model_name='album',
            name='users',
            field=models.ManyToManyField(to='test_app.usermodel', verbose_name='Access to Multiple Users'),
        ),
    ]
